### create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author": "Gorilla",
  "url": "www.testing.com",
  "title": "second blog",
  "likes": 5
}

# {
#   "author": "Allahu Akbar",
#   "title": "Holy Quran",
#   "likes": 111
# }

### delete a blog
DELETE http://localhost:3001/api/blogs/2
Content-Type: application/json

### get all blogs
GET http://localhost:3001/api/blogs
Content-Type: application/json

### update like of a blog
PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
  "likes": 333
}